"""add server version

Revision ID: 99787a31dacb
Revises: b4ed34abc541
Create Date: 2025-09-06 20:44:14.158016

"""

# revision identifiers, used by Alembic.
revision = '99787a31dacb'
down_revision = 'b4ed34abc541'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('version', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'servers', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servers', type_='unique')
    op.drop_column('servers', 'version')
    # ### end Alembic commands ###
